# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# User specific aliases and functions
source ~/bashworks/module/source.sh
module_repo ~/bashworks

[[ $- = *i* ]] && { 
    module interactive;
    source ~/liquidprompt/liquidprompt;
}
