:set sw=4 ts=4 sts=4 et ai nu
:set colorcolumn=78 background=dark
set directory=~/.vim/backups/
cmap w!! w !sudo tee > /dev/null %

iabbrev pulbic public
iabbrev pbulic public
iabbrev fucndtion function
iabbrev functino function
iabbrev fucntion function
iabbrev dfeault default

let g:vim_markdown_folding_disabled=1
